import {
  LayoutDashboard,
  BarChart3,
  Users,
  FolderOpen,
  Building2,
  TrendingUp,
  DollarSign,
  Clock,
  X,
} from "lucide-react";

export const industries = [
  "All",
  "Technology",
  "Finance",
  "Healthcare",
  "Retail",
  "Education",
  "Manufacturing",
];

export const metrics = [
  {
    name: "Revenue",
    value: "$324.2K",
    change: "+12.5%",
    trend: "up",
    icon: DollarSign,
    color: "from-green-500 to-emerald-500",
    bgColor: "from-green-50 to-emerald-50",
  },
  {
    name: "Active Projects",
    value: "24",
    change: "+8.2%",
    trend: "up",
    icon: FolderOpen,
    color: "from-blue-500 to-cyan-500",
    bgColor: "from-blue-50 to-cyan-50",
  },
  {
    name: "Team Utilization",
    value: "87%",
    change: "-2.1%",
    trend: "down",
    icon: Users,
    color: "from-orange-500 to-red-500",
    bgColor: "from-orange-50 to-red-50",
  },
  {
    name: "Avg. Project Time",
    value: "6.2 weeks",
    change: "-5.3%",
    trend: "up",
    icon: Clock,
    color: "from-purple-500 to-violet-500",
    bgColor: "from-purple-50 to-violet-50",
  },
];

export const departmentPerformance = [
  {
    department: "Design",
    projects: 12,
    revenue: "$145,000",
    utilization: 92,
    color: "bg-pink-500",
  },
  {
    department: "Development",
    projects: 8,
    revenue: "$98,000",
    utilization: 85,
    color: "bg-blue-500",
  },
  {
    department: "Marketing",
    projects: 6,
    revenue: "$54,000",
    utilization: 78,
    color: "bg-green-500",
  },
  {
    department: "Strategy",
    projects: 4,
    revenue: "$67,000",
    utilization: 88,
    color: "bg-purple-500",
  },
  {
    department: "Management",
    projects: 16,
    revenue: "$45,000",
    utilization: 95,
    color: "bg-gray-500",
  },
];

export const recentActivity = [
  {
    action: "Project completed",
    details: "Brand Identity - TechCorp",
    time: "2 hours ago",
    type: "success",
  },
  {
    action: "New client onboarded",
    details: "GreenTech Solutions",
    time: "4 hours ago",
    type: "info",
  },
  {
    action: "Project milestone reached",
    details: "Mobile App UI - FinanceApp (75%)",
    time: "6 hours ago",
    type: "success",
  },
  {
    action: "Team member added",
    details: "Jordan Lee joined Development",
    time: "1 day ago",
    type: "info",
  },
  {
    action: "Project delayed",
    details: "Website Redesign - StartupX",
    time: "2 days ago",
    type: "warning",
  },
];

export const clients = [
  {
    id: 1,
    name: "TechCorp Inc.",
    industry: "Technology",
    status: "Active",
    email: "contact@techcorp.com",
    phone: "+1 (555) 123-4567",
    website: "www.techcorp.com",
    location: "San Francisco, CA",
    projects: 3,
    revenue: "$125,000",
    joinDate: "2023-06-15",
    rating: 4.8,
    description:
      "Leading technology solutions provider specializing in enterprise software.",
  },
  {
    id: 2,
    name: "StartupX",
    industry: "Technology",
    status: "Active",
    email: "hello@startupx.io",
    phone: "+1 (555) 234-5678",
    website: "www.startupx.io",
    location: "Austin, TX",
    projects: 2,
    revenue: "$67,000",
    joinDate: "2023-09-20",
    rating: 4.6,
    description: "Innovative startup focused on AI-powered business solutions.",
  },
  {
    id: 3,
    name: "Finance Solutions",
    industry: "Finance",
    status: "Active",
    email: "info@financesolutions.com",
    phone: "+1 (555) 345-6789",
    website: "www.financesolutions.com",
    location: "New York, NY",
    projects: 1,
    revenue: "$78,000",
    joinDate: "2023-08-10",
    rating: 4.9,
    description:
      "Comprehensive financial services and consulting for businesses.",
  },
  {
    id: 4,
    name: "Retail Brand Co.",
    industry: "Retail",
    status: "Prospect",
    email: "marketing@retailbrand.com",
    phone: "+1 (555) 456-7890",
    website: "www.retailbrand.com",
    location: "Los Angeles, CA",
    projects: 0,
    revenue: "$0",
    joinDate: "2024-01-05",
    rating: 0,
    description:
      "Fashion retail chain looking to expand their digital presence.",
  },
  {
    id: 5,
    name: "ShopEasy",
    industry: "Retail",
    status: "Active",
    email: "support@shopeasy.com",
    phone: "+1 (555) 567-8901",
    website: "www.shopeasy.com",
    location: "Seattle, WA",
    projects: 2,
    revenue: "$145,000",
    joinDate: "2023-04-12",
    rating: 4.7,
    description: "E-commerce platform serving thousands of online retailers.",
  },
  {
    id: 6,
    name: "GreenTech Solutions",
    industry: "Technology",
    status: "Active",
    email: "contact@greentech.com",
    phone: "+1 (555) 678-9012",
    website: "www.greentech.com",
    location: "Portland, OR",
    projects: 1,
    revenue: "$32,000",
    joinDate: "2023-11-03",
    rating: 4.5,
    description:
      "Sustainable technology company focused on renewable energy solutions.",
  },
  {
    id: 7,
    name: "HealthFirst",
    industry: "Healthcare",
    status: "Active",
    email: "care@healthfirst.org",
    phone: "+1 (555) 789-0123",
    website: "www.healthfirst.org",
    location: "Chicago, IL",
    projects: 4,
    revenue: "$210,000",
    joinDate: "2023-05-22",
    rating: 4.9,
    description: "Healthcare services provider with national coverage.",
  },
  {
    id: 8,
    name: "EduTech Labs",
    industry: "Education",
    status: "Active",
    email: "info@edutechlabs.com",
    phone: "+1 (555) 890-1234",
    website: "www.edutechlabs.com",
    location: "Boston, MA",
    projects: 3,
    revenue: "$93,000",
    joinDate: "2023-10-01",
    rating: 4.7,
    description: "Developer of digital education tools and learning platforms.",
  },
  {
    id: 9,
    name: "AutoDrive",
    industry: "Automotive",
    status: "Inactive",
    email: "sales@autodrive.com",
    phone: "+1 (555) 901-2345",
    website: "www.autodrive.com",
    location: "Detroit, MI",
    projects: 2,
    revenue: "$58,000",
    joinDate: "2022-12-18",
    rating: 3.9,
    description: "Electric vehicle parts and autonomous driving solutions.",
  },
  {
    id: 10,
    name: "FoodChain Co.",
    industry: "Food & Beverage",
    status: "Prospect",
    email: "info@foodchainco.com",
    phone: "+1 (555) 012-3456",
    website: "www.foodchainco.com",
    location: "Dallas, TX",
    projects: 0,
    revenue: "$0",
    joinDate: "2024-02-11",
    rating: 0,
    description: "Restaurant supply chain and logistics company.",
  },
  {
    id: 11,
    name: "SecureNet",
    industry: "Cybersecurity",
    status: "Active",
    email: "support@securenet.com",
    phone: "+1 (555) 543-2109",
    website: "www.securenet.com",
    location: "San Jose, CA",
    projects: 5,
    revenue: "$300,000",
    joinDate: "2023-07-08",
    rating: 4.8,
    description: "Cybersecurity firm protecting digital infrastructure.",
  },
  {
    id: 12,
    name: "CloudSync",
    industry: "Technology",
    status: "Active",
    email: "connect@cloudsync.io",
    phone: "+1 (555) 210-9876",
    website: "www.cloudsync.io",
    location: "Denver, CO",
    projects: 3,
    revenue: "$142,000",
    joinDate: "2023-06-30",
    rating: 4.4,
    description: "Cloud integration and data sync service provider.",
  },
  {
    id: 13,
    name: "BuildRight",
    industry: "Construction",
    status: "Active",
    email: "info@buildright.com",
    phone: "+1 (555) 321-4567",
    website: "www.buildright.com",
    location: "Phoenix, AZ",
    projects: 4,
    revenue: "$176,000",
    joinDate: "2023-03-14",
    rating: 4.2,
    description: "Commercial and residential construction services.",
  },
  {
    id: 14,
    name: "Eventrix",
    industry: "Events",
    status: "Prospect",
    email: "events@eventrix.com",
    phone: "+1 (555) 432-1098",
    website: "www.eventrix.com",
    location: "Orlando, FL",
    projects: 0,
    revenue: "$0",
    joinDate: "2024-03-01",
    rating: 0,
    description: "Event planning and virtual conference platform.",
  },
  {
    id: 15,
    name: "AgriCore",
    industry: "Agriculture",
    status: "Active",
    email: "contact@agricore.com",
    phone: "+1 (555) 654-3210",
    website: "www.agricore.com",
    location: "Des Moines, IA",
    projects: 1,
    revenue: "$25,000",
    joinDate: "2023-12-02",
    rating: 4.0,
    description: "Tech-driven agricultural solutions and equipment.",
  },
  {
    id: 16,
    name: "DesignIt Studio",
    industry: "Design",
    status: "Active",
    email: "hello@designit.com",
    phone: "+1 (555) 765-4321",
    website: "www.designit.com",
    location: "Brooklyn, NY",
    projects: 2,
    revenue: "$87,000",
    joinDate: "2023-02-28",
    rating: 4.6,
    description: "Creative design agency for branding and UI/UX.",
  },
  {
    id: 17,
    name: "LogiTrans",
    industry: "Logistics",
    status: "Active",
    email: "service@logitrans.com",
    phone: "+1 (555) 876-5432",
    website: "www.logitrans.com",
    location: "Atlanta, GA",
    projects: 2,
    revenue: "$104,000",
    joinDate: "2023-09-01",
    rating: 4.3,
    description: "Global logistics and freight forwarding services.",
  },
  {
    id: 18,
    name: "LegalWise",
    industry: "Legal",
    status: "Active",
    email: "contact@legalwise.com",
    phone: "+1 (555) 987-6543",
    website: "www.legalwise.com",
    location: "Philadelphia, PA",
    projects: 1,
    revenue: "$39,000",
    joinDate: "2023-01-19",
    rating: 4.1,
    description: "Legal advisory services for small to mid-sized firms.",
  },
  {
    id: 19,
    name: "MediaNext",
    industry: "Media",
    status: "Prospect",
    email: "info@medianext.tv",
    phone: "+1 (555) 098-7654",
    website: "www.medianext.tv",
    location: "Los Angeles, CA",
    projects: 0,
    revenue: "$0",
    joinDate: "2024-05-10",
    rating: 0,
    description: "Streaming and multimedia production company.",
  },
  {
    id: 20,
    name: "EcoFresh",
    industry: "Consumer Goods",
    status: "Active",
    email: "hello@ecofresh.com",
    phone: "+1 (555) 109-8765",
    website: "www.ecofresh.com",
    location: "Boulder, CO",
    projects: 2,
    revenue: "$66,000",
    joinDate: "2023-07-25",
    rating: 4.5,
    description: "Organic cleaning products with eco-friendly packaging.",
  },
];

export const departments = [
  "All",
  "Design",
  "Development",
  "Marketing",
  "Strategy",
  "Management",
];

export const stats = [
  {
    name: "Active Projects",
    value: "24",
    change: "+12%",
    icon: FolderOpen,
    color: "from-blue-500 to-cyan-500",
    bgColor: "from-blue-50 to-cyan-50",
  },
  {
    name: "Team Members",
    value: "32",
    change: "+3%",
    icon: Users,
    color: "from-green-500 to-emerald-500",
    bgColor: "from-green-50 to-emerald-50",
  },
  {
    name: "Revenue",
    value: "$89.2K",
    change: "+18%",
    icon: DollarSign,
    color: "from-purple-500 to-violet-500",
    bgColor: "from-purple-50 to-violet-50",
  },
  {
    name: "Growth",
    value: "23.1%",
    change: "+4.2%",
    icon: TrendingUp,
    color: "from-orange-500 to-red-500",
    bgColor: "from-orange-50 to-red-50",
  },
];

export const recentProjects = [
  {
    name: "Brand Identity - TechCorp",
    client: "TechCorp Inc.",
    status: "In Progress",
    progress: 75,
    dueDate: "2 days",
    priority: "High",
  },
  {
    name: "Website Redesign - StartupX",
    client: "StartupX",
    status: "Review",
    progress: 90,
    dueDate: "5 days",
    priority: "Medium",
  },
  {
    name: "Mobile App UI - FinanceApp",
    client: "Finance Solutions",
    status: "In Progress",
    progress: 45,
    dueDate: "1 week",
    priority: "Critical",
  },
  {
    name: "Marketing Campaign - RetailBrand",
    client: "Retail Brand Co.",
    status: "Planning",
    progress: 20,
    dueDate: "3 weeks",
    priority: "Low",
  },
];

export const statuses = [
  "All",
  "Planning",
  "In Progress",
  "Review",
  "Completed",
];

export const projects = [
  {
    id: 1,
    name: "Brand Identity - TechCorp",
    client: "TechCorp Inc.",
    status: "In Progress",
    priority: "High",
    budget: "$45,000",
    deadline: "2024-02-15",
    progress: 75,
    team: [
      "ejvkszrm12098467",
      "ubyzsvqt20743958",
      "pvacqsjm62870413",
      "dsyebngt26831957",
      "tmiraxwl10784529",
    ],
    description:
      "Complete brand identity redesign including logo, color palette, and brand guidelines.",
  },
  {
    id: 2,
    name: "Website Redesign - StartupX",
    client: "StartupX",
    status: "Review",
    priority: "Medium",
    budget: "$32,000",
    deadline: "2024-01-30",
    progress: 90,
    team: [
      "pvacqsjm62870413",
      "ikndbzux79126538",
      "vmteyqhr40319725",
      "zulpbcdt85940361",
      "ejvkszrm12098467",
    ],
    description:
      "Modern website redesign with improved UX and mobile responsiveness.",
  },
  {
    id: 3,
    name: "Mobile App UI - FinanceApp",
    client: "Finance Solutions",
    status: "In Progress",
    priority: "Critical",
    budget: "$78,000",
    deadline: "2024-03-20",
    progress: 45,
    team: [
      "xayqrjvb98324051",
      "trmjbnwe62015849",
      "bocwzxur73190426",
      "gytmeqih19048265",
      "zxfwahvu80723194",
      "wjrhzstc25987043",
      "eqbyxtnl13490785",
      "ldpoavqh68902137",
    ],
    description:
      "Native mobile app design for iOS and Android with advanced financial features.",
  },
  {
    id: 4,
    name: "Marketing Campaign - RetailBrand",
    client: "Retail Brand Co.",
    status: "Planning",
    priority: "Medium",
    budget: "$25,000",
    deadline: "2024-02-28",
    progress: 20,
    team: ["nxzduryg35018469", "pvacqsjm62870413", "ikndbzux79126538"],
    description:
      "Comprehensive marketing campaign including digital ads and social media strategy.",
  },
  {
    id: 5,
    name: "E-commerce Platform",
    client: "ShopEasy",
    status: "Completed",
    priority: "High",
    budget: "$95,000",
    deadline: "2024-01-15",
    progress: 100,
    team: [
      "lxqvgeum59273184",
      "ocuzhknd83916042",
      "tmiraxwl10784529",
      "dsyebngt26831957",
      "bwvaxzle43018276",
    ],
    description:
      "Full-stack e-commerce platform with payment integration and inventory management.",
  },
  {
    id: 6,
    name: "Logo Design - GreenTech",
    client: "GreenTech Solutions",
    status: "In Progress",
    priority: "Low",
    budget: "$8,000",
    deadline: "2024-02-10",
    progress: 60,
    team: [
      "yfpmxwac54378190",
      "ubyzsvqt20743958",
      "lmcsqogi86102379",
      "nkpzyldw40578136",
    ],
    description: "Modern logo design for sustainable technology company.",
  },
];

export const priorities = ["All", "Low", "Medium", "High", "Critical"];

export const navigation = [
  { name: "Dashboard", href: "dashboard", icon: LayoutDashboard },
  { name: "Analytics", href: "analytics", icon: BarChart3 },
  { name: "Teams", href: "teams", icon: Users },
  { name: "Projects", href: "projects", icon: FolderOpen },
  { name: "Clients", href: "clients", icon: Building2 },
  // { name: "Test", href: "test", icon: Building2 },
];

export const teamMembers = [
  {
    id: "lxqvgeum59273184",
    name: "Emma Johnson",
    role: "UI/UX Designer",
    department: "Design",
    email: "emma.johnson@designpro.com",
    phone: "+1 (555) 123-4567",
    image: "/images/a-fotor-ai-f202506290103.jpg",
    status: "Available",
    projects: 2,
    location: "New York",
    rating: 4.7,
    color: "from-pink-500 to-rose-500",
  },
  {
    id: "ocuzhknd83916042",
    name: "Olivia Smith",
    role: "Full Stack Developer",
    department: "Development",
    email: "olivia.smith@designpro.com",
    phone: "+1 (555) 234-5678",
    image: "/images/a-fotor-ai-f202506290103-1.jpg",
    status: "Busy",
    projects: 3,
    location: "San Francisco",
    rating: 4.8,
    color: "from-blue-500 to-indigo-500",
  },
  {
    id: "tmiraxwl10784529",
    name: "Ava Patel",
    role: "Product Manager",
    department: "Product",
    email: "ava.patel@designpro.com",
    phone: "+1 (555) 345-6789",
    image: "/images/a-fotor-ai-f202506290623.jpg",
    status: "Available",
    projects: 5,
    location: "Austin",
    rating: 4.9,
    color: "from-green-500 to-teal-500",
  },
  {
    id: "dsyebngt26831957",
    name: "Sophia Reyes",
    role: "QA Engineer",
    department: "Quality Assurance",
    email: "sophia.reyes@designpro.com",
    phone: "+1 (555) 456-7890",
    image: "",
    status: "Available",
    projects: 2,
    location: "Chicago",
    rating: 4.6,
    color: "from-yellow-400 to-yellow-600",
  },
  {
    id: "bwvaxzle43018276",
    name: "Isabella Kim",
    role: "Frontend Developer",
    department: "Development",
    email: "isabella.kim@designpro.com",
    phone: "+1 (555) 567-8901",
    image: "/images/a-fotor-ai-f202506290634.jpg",
    status: "Busy",
    projects: 4,
    location: "Los Angeles",
    rating: 4.5,
    color: "from-purple-500 to-violet-600",
  },
  {
    id: "qhjoftnm98741253",
    name: "Mia Thompson",
    role: "Marketing Manager",
    department: "Marketing",
    email: "mia.thompson@designpro.com",
    phone: "+1 (555) 678-9012",
    image: "/images/a-fotor-ai-f202506290954.jpg",
    status: "On Leave",
    projects: 1,
    location: "Miami",
    rating: 4.2,
    color: "from-orange-400 to-red-500",
  },
  {
    id: "nxzduryg35018469",
    name: "Charlotte Nguyen",
    role: "Data Analyst",
    department: "Analytics",
    email: "charlotte.nguyen@designpro.com",
    phone: "+1 (555) 789-0123",
    image: "/images/a-fotor-ai-f202506290954-1.jpg",
    status: "Available",
    projects: 3,
    location: "Seattle",
    rating: 4.8,
    color: "from-teal-500 to-emerald-500",
  },
  {
    id: "pvacqsjm62870413",
    name: "Amelia Garcia",
    role: "DevOps Engineer",
    department: "Infrastructure",
    email: "amelia.garcia@designpro.com",
    phone: "+1 (555) 890-1234",
    image: "/images/a-fotor-ai-f20250628235043.jpg",
    status: "Busy",
    projects: 2,
    location: "Denver",
    rating: 4.6,
    color: "from-gray-600 to-zinc-700",
  },
  {
    id: "ikndbzux79126538",
    name: "Harper Brooks",
    role: "Business Analyst",
    department: "Product",
    email: "harper.brooks@designpro.com",
    phone: "+1 (555) 901-2345",
    image: "/images/a-fotor-ai-f20250628235049.jpg",
    status: "Available",
    projects: 2,
    location: "Boston",
    rating: 4.7,
    color: "from-fuchsia-500 to-pink-600",
  },
  {
    id: "kkzfb1jvqmg43xip",
    name: "Bob Perez",
    role: "Strategy",
    department: "Strategy",
    email: "bob.perez@designpro.com",
    phone: "+1 (555) 493-1068",
    image: "",
    status: "Busy",
    projects: 2,
    location: "Houston",
    rating: 4.8,
    color: "from-green-500 to-teal-500",
  },
  {
    id: "nkzifo23nsze8gd0",
    name: "Yara Brown",
    role: "Development",
    department: "Development",
    email: "yara.brown@designpro.com",
    phone: "+1 (555) 973-5784",
    image: "",
    status: "Available",
    projects: 2,
    location: "San Diego",
    rating: 4.0,
    color: "from-cyan-500 to-sky-500",
  },
  {
    id: "kjjq08j16572ix36",
    name: "Alice Robinson",
    role: "Development",
    department: "Development",
    email: "alice.robinson@designpro.com",
    phone: "+1 (555) 599-2136",
    image: "",
    status: "Busy",
    projects: 2,
    location: "San Diego",
    rating: 4.2,
    color: "from-indigo-500 to-purple-600",
  },
  {
    id: "v51bwxdi8abwk7iq",
    name: "Victor Rodriguez",
    role: "Development",
    department: "Development",
    email: "victor.rodriguez@designpro.com",
    phone: "+1 (555) 760-7343",
    image: "",
    status: "On Leave",
    projects: 5,
    location: "New York",
    rating: 4.5,
    color: "from-lime-400 to-green-500",
  },
  {
    id: "8scl8g4lc24fma2a",
    name: "Victor Williams",
    role: "Management",
    department: "Management",
    email: "victor.williams@designpro.com",
    phone: "+1 (555) 504-8849",
    image: "",
    status: "Available",
    projects: 2,
    location: "Salt Lake City",
    rating: 4.4,
    color: "from-indigo-500 to-purple-600",
  },
  {
    id: "vucarirapc02mmvk",
    name: "Hannah Wilson",
    role: "Marketing",
    department: "Marketing",
    email: "hannah.wilson@designpro.com",
    phone: "+1 (555) 567-1533",
    image: "",
    status: "On Leave",
    projects: 2,
    location: "San Francisco",
    rating: 4.0,
    color: "from-violet-500 to-purple-600",
  },
  {
    id: "brnj3oklke3goqcn",
    name: "Ethan Martin",
    role: "Strategy",
    department: "Strategy",
    email: "ethan.martin@designpro.com",
    phone: "+1 (555) 752-2460",
    image: "",
    status: "Busy",
    projects: 4,
    location: "Seattle",
    rating: 4.5,
    color: "from-slate-500 to-slate-700",
  },
  {
    id: "ca9i7m9ern3jsc5l",
    name: "Kevin Martin",
    role: "Management",
    department: "Management",
    email: "kevin.martin@designpro.com",
    phone: "+1 (555) 699-3952",
    image: "",
    status: "On Leave",
    projects: 3,
    location: "Chicago",
    rating: 3.5,
    color: "from-amber-400 to-orange-500",
  },
  {
    id: "tnpgo5m5q356d7mb",
    name: "Debra Wilson",
    role: "Strategy",
    department: "Strategy",
    email: "debra.wilson@designpro.com",
    phone: "+1 (555) 557-4490",
    image: "",
    status: "Busy",
    projects: 2,
    location: "Phoenix",
    rating: 4.6,
    color: "from-slate-500 to-slate-700",
  },
  {
    id: "8qa83zm1kpxackeh",
    name: "Ivan Ramirez",
    role: "Management",
    department: "Management",
    email: "ivan.ramirez@designpro.com",
    phone: "+1 (555) 238-8935",
    image: "",
    status: "Busy",
    projects: 2,
    location: "Los Angeles",
    rating: 4.1,
    color: "from-lime-500 to-green-400",
  },
  {
    id: "14kfndbqquu2mr09",
    name: "Frank Thompson",
    role: "Marketing",
    department: "Marketing",
    email: "frank.thompson@designpro.com",
    phone: "+1 (555) 962-8607",
    image: "",
    status: "On Leave",
    projects: 2,
    location: "Houston",
    rating: 4.0,
    color: "from-emerald-500 to-green-600",
  },
  {
    id: "arowqwiv5f36po3u",
    name: "Zack Davis",
    role: "Development",
    department: "Development",
    email: "zack.davis@designpro.com",
    phone: "+1 (555) 659-9108",
    image: "",
    status: "Available",
    projects: 5,
    location: "Houston",
    rating: 4.7,
    color: "from-indigo-500 to-blue-600",
  },
  {
    id: "9v81wb77ytf2x244",
    name: "Brenda Anderson",
    role: "Development",
    department: "Development",
    email: "brenda.anderson@designpro.com",
    phone: "+1 (555) 751-9070",
    image: "",
    status: "On Leave",
    projects: 3,
    location: "Dallas",
    rating: 4.2,
    color: "from-lime-400 to-green-500",
  },
  {
    id: "2iz9j3n7x5ygz4wi",
    name: "Diana Miller",
    role: "Development",
    department: "Development",
    email: "diana.miller@designpro.com",
    phone: "+1 (555) 118-8298",
    image: "",
    status: "Available",
    projects: 5,
    location: "Miami",
    rating: 3.2,
    color: "from-blue-400 to-indigo-600",
  },
  {
    id: "e7c577st6ushg254",
    name: "Nancy Wilson",
    role: "Management",
    department: "Management",
    email: "nancy.wilson@designpro.com",
    phone: "+1 (555) 354-5516",
    image: "",
    status: "On Leave",
    projects: 4,
    location: "Houston",
    rating: 4.5,
    color: "from-indigo-500 to-blue-600",
  },
  {
    id: "1gf6guy958qpn7v1",
    name: "Zack Smith",
    role: "Management",
    department: "Management",
    email: "zack.smith@designpro.com",
    phone: "+1 (555) 104-6332",
    image: "",
    status: "Available",
    projects: 3,
    location: "Los Angeles",
    rating: 4.2,
    color: "from-blue-500 to-indigo-500",
  },
  {
    id: "0itqfihzsk4gj0em",
    name: "Pamela Robinson",
    role: "Marketing",
    department: "Marketing",
    email: "pamela.robinson@designpro.com",
    phone: "+1 (555) 287-4901",
    image: "",
    status: "Available",
    projects: 5,
    location: "Denver",
    rating: 4.2,
    color: "from-indigo-500 to-purple-600",
  },
  {
    id: "51kc3l0zdrn679sy",
    name: "Tina Miller",
    role: "Management",
    department: "Management",
    email: "tina.miller@designpro.com",
    phone: "+1 (555) 909-6777",
    image: "",
    status: "Busy",
    projects: 2,
    location: "Las Vegas",
    rating: 4.1,
    color: "from-green-500 to-teal-500",
  },
  {
    id: "ymwrjwsjrwfvxhf4",
    name: "Uma Rodriguez",
    role: "Design",
    department: "Design",
    email: "uma.rodriguez@designpro.com",
    phone: "+1 (555) 660-4540",
    image: "",
    status: "Busy",
    projects: 3,
    location: "Dallas",
    rating: 4.1,
    color: "from-sky-400 to-blue-500",
  },
  {
    id: "h1zn59z6110hyjeb",
    name: "Rachel Taylor",
    role: "Strategy",
    department: "Strategy",
    email: "rachel.taylor@designpro.com",
    phone: "+1 (555) 805-3356",
    image: "",
    status: "Busy",
    projects: 1,
    location: "Chicago",
    rating: 3.8,
    color: "from-indigo-500 to-purple-600",
  },
  {
    id: "1dovzrpuw97hgoau",
    name: "Nancy White",
    role: "Design",
    department: "Design",
    email: "nancy.white@designpro.com",
    phone: "+1 (555) 739-3568",
    image: "",
    status: "Available",
    projects: 5,
    location: "Las Vegas",
    rating: 4.8,
    color: "from-purple-500 to-violet-600",
  },
  {
    id: "j84tm220483kqv0u",
    name: "Laura Harris",
    role: "Development",
    department: "Development",
    email: "laura.harris@designpro.com",
    phone: "+1 (555) 897-8159",
    image: "",
    status: "On Leave",
    projects: 5,
    location: "San Francisco",
    rating: 3.9,
    color: "from-blue-500 to-indigo-500",
  },
  {
    id: "fy8nflotq6vjstyr",
    name: "Alice Rodriguez",
    role: "Management",
    department: "Management",
    email: "alice.rodriguez@designpro.com",
    phone: "+1 (555) 347-6096",
    image: "",
    status: "Busy",
    projects: 4,
    location: "Dallas",
    rating: 3.1,
    color: "from-emerald-500 to-green-600",
  },
  {
    id: "0xn1rrn8kalzb1gw",
    name: "Victor White",
    role: "Management",
    department: "Management",
    email: "victor.white@designpro.com",
    phone: "+1 (555) 568-3330",
    image: "",
    status: "Available",
    projects: 4,
    location: "Charlotte",
    rating: 3.0,
    color: "from-fuchsia-500 to-pink-600",
  },
  {
    id: "4ge2iz7urq6rxgom",
    name: "Steve Taylor",
    role: "Marketing",
    department: "Marketing",
    email: "steve.taylor@designpro.com",
    phone: "+1 (555) 125-4059",
    image: "",
    status: "On Leave",
    projects: 5,
    location: "Atlanta",
    rating: 3.5,
    color: "from-red-400 to-rose-600",
  },
  {
    id: "5svtiu52n8u1vw81",
    name: "Debra Clark",
    role: "Design",
    department: "Design",
    email: "debra.clark@designpro.com",
    phone: "+1 (555) 596-4374",
    image: "",
    status: "On Leave",
    projects: 4,
    location: "San Diego",
    rating: 3.4,
    color: "from-slate-500 to-slate-700",
  },
  {
    id: "0cvyk4vizxw5zaa4",
    name: "Ethan Robinson",
    role: "Design",
    department: "Design",
    email: "ethan.robinson@designpro.com",
    phone: "+1 (555) 248-7270",
    image: "",
    status: "Available",
    projects: 3,
    location: "Las Vegas",
    rating: 4.5,
    color: "from-yellow-400 to-amber-500",
  },
  {
    id: "7dhm5ijsqi0u6zbb",
    name: "Yara Garcia",
    role: "Development",
    department: "Development",
    email: "yara.garcia@designpro.com",
    phone: "+1 (555) 465-4938",
    image: "",
    status: "Busy",
    projects: 3,
    location: "San Diego",
    rating: 4.1,
    color: "from-yellow-400 to-amber-500",
  },
  {
    id: "wog3xazm2sm7yw4u",
    name: "Quinn Gonzalez",
    role: "Management",
    department: "Management",
    email: "quinn.gonzalez@designpro.com",
    phone: "+1 (555) 158-1839",
    image: "",
    status: "Busy",
    projects: 5,
    location: "New York",
    rating: 3.3,
    color: "from-fuchsia-500 to-pink-600",
  },
  {
    id: "yros5bk6ys11ijvm",
    name: "Steve Gonzalez",
    role: "Development",
    department: "Development",
    email: "steve.gonzalez@designpro.com",
    phone: "+1 (555) 303-4843",
    image: "",
    status: "Available",
    projects: 3,
    location: "Las Vegas",
    rating: 4.9,
    color: "from-indigo-500 to-purple-600",
  },
  {
    id: "vmteyqhr40319725",
    name: "Evelyn Martinez",
    role: "HR Manager",
    department: "Human Resources",
    email: "evelyn.martinez@designpro.com",
    phone: "+1 (555) 012-3456",
    image: "/images/a-fotor-ai-f20250628235158.jpg",
    status: "Busy",
    projects: 1,
    location: "Atlanta",
    rating: 4.5,
    color: "from-amber-400 to-orange-500",
  },
  {
    id: "zulpbcdt85940361",
    name: "Abigail Lee",
    role: "Scrum Master",
    department: "Project Management",
    email: "abigail.lee@designpro.com",
    phone: "+1 (555) 111-2233",
    image: "/images/a-fotor-ai-f20250628235212.jpg",
    status: "Available",
    projects: 4,
    location: "Philadelphia",
    rating: 4.9,
    color: "from-cyan-500 to-sky-500",
  },

  {
    id: "ejvkszrm12098467",
    name: "Ella Rivera",
    role: "Graphic Designer",
    department: "Design",
    email: "ella.rivera@designpro.com",
    phone: "+1 (555) 222-3344",
    image: "",
    status: "Busy",
    projects: 2,
    location: "Las Vegas",
    rating: 4.3,
    color: "from-pink-400 to-rose-500",
  },
  {
    id: "txfycwgn38417520",
    name: "Scarlett Cruz",
    role: "SEO Specialist",
    department: "Marketing",
    email: "scarlett.cruz@designpro.com",
    phone: "+1 (555) 333-4455",
    image: "/images/a-fotor-ai-f20250628235549.jpg",
    status: "Available",
    projects: 1,
    location: "Phoenix",
    rating: 4.1,
    color: "from-lime-400 to-green-500",
  },
  {
    id: "kwotnlhz67903182",
    name: "Grace Morgan",
    role: "Technical Writer",
    department: "Documentation",
    email: "grace.morgan@designpro.com",
    phone: "+1 (555) 444-5566",
    image: "/images/a-fotor-ai-f20250628235647.jpg",
    status: "Available",
    projects: 2,
    location: "Salt Lake City",
    rating: 4.4,
    color: "from-indigo-500 to-purple-600",
  },
  {
    id: "sgejrbxf19482063",
    name: "Chloe Adams",
    role: "Support Specialist",
    department: "Customer Support",
    email: "chloe.adams@designpro.com",
    phone: "+1 (555) 555-6677",
    image: "/images/a-fotor-ai-f20250628235652.jpg",
    status: "Busy",
    projects: 1,
    location: "Minneapolis",
    rating: 4.2,
    color: "from-red-400 to-rose-600",
  },
  {
    id: "yfpmxwac54378190",
    name: "Victoria Torres",
    role: "Content Strategist",
    department: "Content",
    email: "victoria.torres@designpro.com",
    phone: "+1 (555) 666-7788",
    image: "/images/a-fotor-ai-f24620328235681.jpg",
    status: "Available",
    projects: 3,
    location: "San Diego",
    rating: 4.6,
    color: "from-blue-400 to-indigo-600",
  },
  {
    id: "ubyzsvqt20743958",
    name: "Liam Anderson",
    role: "Full Stack Developer",
    department: "Development",
    email: "liam.anderson@designpro.com",
    phone: "+1 (555) 101-1010",
    image: "/images/a-fotor-ai-m20250629057.jpg",
    status: "Busy",
    projects: 4,
    location: "San Francisco",
    rating: 4.7,
    color: "from-blue-600 to-indigo-600",
  },
  {
    id: "lmcsqogi86102379",
    name: "Noah Brooks",
    role: "Backend Developer",
    department: "Development",
    email: "noah.brooks@designpro.com",
    phone: "+1 (555) 202-2020",
    image: "/images/a-fotor-ai-m202506290459.jpg",
    status: "Available",
    projects: 3,
    location: "Austin",
    rating: 4.5,
    color: "from-gray-700 to-zinc-800",
  },
  {
    id: "nkpzyldw40578136",
    name: "Oliver Chen",
    role: "Frontend Developer",
    department: "Development",
    email: "oliver.chen@designpro.com",
    phone: "+1 (555) 303-3030",
    image: "/images/a-fotor-ai-m202506290634.jpg",
    status: "Busy",
    projects: 2,
    location: "Seattle",
    rating: 4.6,
    color: "from-violet-500 to-purple-600",
  },
  {
    id: "xayqrjvb98324051",
    name: "Elijah Davis",
    role: "Product Manager",
    department: "Product",
    email: "elijah.davis@designpro.com",
    phone: "+1 (555) 404-4040",
    image: "/images/a-fotor-ai-m202506290726.jpg",
    status: "Available",
    projects: 5,
    location: "New York",
    rating: 4.8,
    color: "from-green-500 to-teal-600",
  },
  {
    id: "trmjbnwe62015849",
    name: "James Evans",
    role: "DevOps Engineer",
    department: "Infrastructure",
    email: "james.evans@designpro.com",
    phone: "+1 (555) 505-5050",
    image: "/images/a-fotor-ai-m202506290726-1.jpg",
    status: "On Leave",
    projects: 1,
    location: "Denver",
    rating: 4.3,
    color: "from-slate-500 to-slate-700",
  },
  {
    id: "bocwzxur73190426",
    name: "Benjamin Foster",
    role: "QA Tester",
    department: "Quality Assurance",
    email: "benjamin.foster@designpro.com",
    phone: "+1 (555) 606-6060",
    image: "/images/a-fotor-ai-m202506290735.jpg",
    status: "Busy",
    projects: 3,
    location: "Boston",
    rating: 4.4,
    color: "from-yellow-400 to-amber-500",
  },
  {
    id: "gytmeqih19048265",
    name: "Lucas Green",
    role: "Data Scientist",
    department: "Analytics",
    email: "lucas.green@designpro.com",
    phone: "+1 (555) 707-7070",
    image: "/images/a-fotor-ai-m2025062823532.jpg",
    status: "Available",
    projects: 4,
    location: "Chicago",
    rating: 4.9,
    color: "from-cyan-500 to-blue-500",
  },
  {
    id: "zxfwahvu80723194",
    name: "Henry Hall",
    role: "Scrum Master",
    department: "Project Management",
    email: "henry.hall@designpro.com",
    phone: "+1 (555) 808-8080",
    image: "/images/a-fotor-ai-m2025062823580.jpg",
    status: "Busy",
    projects: 3,
    location: "Los Angeles",
    rating: 4.5,
    color: "from-red-400 to-rose-600",
  },
  {
    id: "wjrhzstc25987043",
    name: "Alexander Ivanov",
    role: "Security Engineer",
    department: "Security",
    email: "alexander.ivanov@designpro.com",
    phone: "+1 (555) 909-9090",
    image: "/images/a-fotor-ai-m20250628234924.jpg",
    status: "Available",
    projects: 2,
    location: "Philadelphia",
    rating: 4.6,
    color: "from-emerald-500 to-green-600",
  },
  {
    id: "eqbyxtnl13490785",
    name: "Michael Jackson",
    role: "Tech Lead",
    department: "Development",
    email: "michael.jackson@designpro.com",
    phone: "+1 (555) 010-1010",
    image: "/images/a-fotor-ai-m20250628234933.jpg",
    status: "Busy",
    projects: 5,
    location: "Houston",
    rating: 4.9,
    color: "from-fuchsia-500 to-pink-600",
  },
  {
    id: "ldpoavqh68902137",
    name: "Daniel Kim",
    role: "Cloud Architect",
    department: "Infrastructure",
    email: "daniel.kim@designpro.com",
    phone: "+1 (555) 111-1212",
    image: "/images/a-fotor-ai-m20250628235253.jpg",
    status: "Available",
    projects: 3,
    location: "Phoenix",
    rating: 4.7,
    color: "from-indigo-500 to-blue-600",
  },
  {
    id: "mjhnctgz79014568",
    name: "Matthew Lopez",
    role: "Content Strategist",
    department: "Content",
    email: "matthew.lopez@designpro.com",
    phone: "+1 (555) 212-2323",
    image: "/images/a-fotor-ai-m20250628235459.jpg",
    status: "Busy",
    projects: 2,
    location: "Las Vegas",
    rating: 4.2,
    color: "from-lime-500 to-green-400",
  },
  {
    id: "vrzqduil30296487",
    name: "David Nguyen",
    role: "Management",
    department: "Product",
    email: "david.nguyen@designpro.com",
    phone: "+1 (555) 313-3333",
    image: "/images/a-fotor-ai-m20250628235512.jpg",
    status: "Available",
    projects: 3,
    location: "Charlotte",
    rating: 4.6,
    color: "from-sky-400 to-blue-500",
  },
  {
    id: "higjexws87421095",
    name: "Jack Wilson",
    role: "Technical Writer",
    department: "Documentation",
    email: "jack.wilson@designpro.com",
    phone: "+1 (555) 414-4444",
    image: "/images/a-fotor-ai-m20250628235756.jpg",
    status: "On Leave",
    projects: 1,
    location: "Salt Lake City",
    rating: 4.1,
    color: "from-gray-500 to-gray-700",
  },
];
